### ISSUE TITLE
Not working at all

### ISSUE THREAD

**Issue by MusicTP** [BobSmithIV/TagProRandomFlairs#2]
hi, I installed the script and it is not working at all. i tried disabling my other scripts and etc. I know it doesn't need an update as someone else I know is using it fine with 10+ other scripts. Could it be a problem with chrome? Please contact me on my reddit account @/u/sounds_goood
Thanks, 
Music

**Comment by BobSmithIV** [comment]
Hi, I'm afraid I haven't touched this in a year or so, in particular since the new website design was released, so I'm surprised someone else has it working!  If I've got a chance I'll take a look at it sometime, but I'm pretty busy right now and haven't visited TagPro myself for some time.  Maybe ask the person who's got it working if they've changed it, and to make a pull request here if they have?

**Comment by BobSmithIV** [comment]
I've found some time to fix this now, all should now be working fine!  Let me know if it doesn't work for you now!
